os: linux
language: php
dist: xenial

jobs:
  include:
      env:
      - XDEBUG_MODE=coverage
      after_script:
      - wget https://scrutinizer-ci.com/ocular.phar
      - php ocular.phar code-coverage:upload --format=php-clover test/build/clover.xml
    - php: 8.0
    - php: 8.1
    - php: 8.2

before_script:
  - composer install --dev --prefer-source

script:
  - php test/test.php
