name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '8.0'
          - '8.1'
        coverage:
          - none
        include:
          - php: '8.2'
            coverage: xdebug
    steps:
      - uses: shivammathur/setup-php@2.26.0
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ matrix.coverage }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2 # min. depth of 2 required by Scrutinizer
      - run: composer install --no-progress --no-ansi --no-interaction --dev --prefer-dist
      - run: php test/test.php
      - if: github.repository == 'mindplay-dk/unbox' && matrix.coverage == 'xdebug'
        uses: sudo-bot/action-scrutinizer@latest
        with:
          cli-args: '--format=php-clover test/build/clover.xml'
